# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.2.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

gem "middleman-blog"

gem "middleman-syntax"

gem "nokogiri"

gem "builder"

gem "redcarpet"

gem 'therubyracer'
gem "less"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]
