# Build and test datafu-spark code for the latest Scala/Spark combinations for the main branch and new PRs
name: "tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '36 3 * * 5'

jobs:
  analyze:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Java 8
      uses: actions/setup-java@v2
      with:
         java-version: '8'
         distribution: 'adopt'
         cache: 'gradle'


    - name: Set up Python      
      uses: actions/setup-python@v4
      with:
         python-version: '2.x'

    - name: Bootstrap Gradle 5.6.4
      run:
       gradle -b bootstrap.gradle

    - name: Build and run tests
      run:
       ./datafu-spark/build_and_test_spark.sh -q
